GET http://localhost:3000/states/
###API 1 get all states
GET http://localhost:3000/states/:stateId/
###API 2 get a state by stateId
POST http://localhost:3000/districts/
### API 3 create district
GET http://localhost:3000/states/:stateId/
### API 4 get a district by districtId
DELETE http://localhost:3000/districts/:districtId/
###  API 5 delete a district by district Id
PUT http://localhost:3000/districts/:districtId/
### API 6 update details of district by districtId

GET http://localhost:3000/states/:stateId/stats/
### API 7 total case,cured,acitve,death
### using SUM AGGREGATION

GET http://localhost:3000/districts/:districtId/details/
### API 8 return a state using district id

